openapi: 3.1.1
info:
  title: Minha API
  describe: Projeto de uma API REST desenvolvida com Expressjs
  version: 0.1.0
servers:
  - url: http://localhost:3000/
    description: Ambiente de Desenvolvimento
tags:
  - tarefas
paths:
  /tarefas:
    get:
      summary: Lista todas tarefas
      tags:
        - tarefas
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfTarefas'
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro500'
    post:
      summary: Cria uma nova tarefa
      tags:
        - tarefas
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tarefa'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro422'
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro500'
  /tarefas/id:
    get:
      summary: Lista uma tarefa
      tags:
        - tarefas
      parameters:
        - in: path
          name: tarefaId
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tarefa'
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro400'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro404'
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro500'
    put:
      security:
         - JWTAuth: []
      summary: Edita uma tarefa
      tags:
        - tarefas
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      parameters:
        - in: path
          name: tarefaId
          required: true
          schema:
            type: integer
          properties:
            nome: 
              type: string
            concluida:
              type: boolean
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tarefa'
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro400'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro404'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro422'
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro500'
    delete:
      summary: Deleta uma tarefa
      description: Descrição aqui
      tags:
        - tarefas
      parameters:
        - in: path
          name: tarefaId
          required: true
          schema:
            type: integer
      responses:
        204:
          content:
            application/json:
              schema:
                type: object
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro400'
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro404'
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro500'
components:
  schemas:
    Tarefa:
      type: object
      properties:
        _id:
          type: string
        nome:
          type: string
        concluida:
          type: boolean
    ArrayOfTarefas:
      type: array
      items:
        $ref: '#/components/schemas/Tarefa'
    Erro400:
      type: object
      properties:
        msg:
          type: string
          example: "Id inválido"
    Erro404:
      type: object
      properties:
        msg:
          type: string
          example: "Tarefa não encontrada"
    Erro422:
      type: object
      properties:
        msg:
          type: string
          example: "Nome é obrigatório"
    Erro500:
      type: object
      properties:
        msg:
          type: string
          example: "Erro interno do servidor"
  securitySchemes:
    JWTAuth: 
      type: apiKey
      in: header
      name: Authorization
      